### PR TITLE
fix: update @async/specs to version 4.0.0 and fix tests (#188)

### LINKED ISSUE #188: Server do not work out of the box with new `@asyncapi/specs` 4.0
#### Describe the bug
Tests are failing with new version -> https://github.com/asyncapi/server-api/actions/runs/3298011137/jobs/5439567189
So the bump cannot be performed -> https://github.com/asyncapi/server-api/pull/184

#### How to Reproduce
Get locally PR with bump `gh pr checkout 184` and run tests

#### Expected behavior

It should work out of the box, as in 4.0 what we did was that we just removed old specs from the package, prior 2.0

### PR DESCRIPTION
**Pull request by vinibiavatti1**
**Description**
- Changed `@asyncapi/specs` to version `4.0.0`
- Removed `openapi.yaml` unsupported versions
- Fixed `convert.controller.test.ts` and `convert.service.test.ts` to work on `4.0.0` version
- Fixed `convert.service.test.ts` to cast specs versions to SpecsEnum

**Related issue(s)**

Resolves #188

### CODE REVIEW

**Comment by BOLT04** [comment]
hi @vinibiavatti1, thanks for the contribution 😃. It seems the docker build is failing, can you try and check what is the problem locally?
It seems it's `error TS2666: Exports and export assignments are not permitted in module augmentations.`

**Comment by magicmatatjahu** [comment]
@vinibiavatti1 as @BOLT04 wrote, please check if locally it works, and if not, please update typescript to the latest version (in package.json) and check again.

In other projects new dependency works.

**Comment by vinibiavatti1** [comment]
Hi @BOLT04 and @magicmatatjahu 
I tested locally and had the same error. After search a bit, I noticed that the problem is with the index.d.ts file, that has a wrong definition for the target file in which is a commonjs file type. I oppened a PR to the spec project with the fix. Here is the link:
https://github.com/asyncapi/spec-json-schemas/pull/288

**Comment by magicmatatjahu** [comment]
@vinibiavatti1 You can update dep to the `4.0.1` :)

**Comment by BOLT04** [comment]
@vinibiavatti1 the docker build is passing now 🎉, we just need to update `package-lock.json` and we can merge 👍

**Review by magicmatatjahu — APPROVED** [review]
LGTM! :) @BOLT04 Do you wanna add something?

**Comment by vinibiavatti1** [comment]
package-lock updated and branch merged with master ;)

**Review by BOLT04 — APPROVED** [review]
LGTM 🚀 
Noice Key and Peele
